- src/main/java/perf/qdup/JarMain.java
- src/main/java/perf/qdup/Local.java
- src/main/java/perf/qdup/Run.java
- src/main/java/perf/qdup/cmd/Cmd.java
- src/main/java/perf/qdup/cmd/Context.java
- src/main/java/perf/qdup/cmd/ScriptContext.java
- src/main/java/perf/qdup/cmd/ShErrorObserver.java
- src/main/java/perf/qdup/cmd/SyncContext.java
- src/main/java/perf/qdup/cmd/impl/Abort.java
- src/main/java/perf/qdup/cmd/impl/Reboot.java
- src/main/java/perf/qdup/config/CmdBuilder.java
- src/test/java/perf/qdup/RunTest.java
- src/test/java/perf/qdup/cmd/SpyContext.java
- src/test/java/perf/qdup/config/RunConfigBuilderTest.java
@willr3 please can you review this change to the abort cmd. I have added a "skipCleanup" parameter that allows me to skip any cleanup steps that have been defined
> #33 Add abort cmd parameter to cleanup scripts

- src/main/java/io/hyperfoil/tools/qdup/config/yaml/Parser.java
- src/test/java/io/hyperfoil/tools/qdup/SshTestBase.java
> fix depricated

- src/main/java/io/hyperfoil/tools/qdup/config/yaml/Parser.java
- src/test/java/io/hyperfoil/tools/qdup/SshTestBase.java
- src/test/java/io/hyperfoil/tools/qdup/cmd/CmdTest.java
> CmdTest timeout

- README.md
> Adjusted path to reference material.

- docs/howto/watch.adoc
- How to watch a command line by line
> howto watch

- docs/howto/script.adoc
- How to call a script from another script
> howto script

- docs/howto/state.adoc
- docs/reference/states.adoc
> howto state

- docs/howto/secrets.adoc
- How to pass secrets into qDup
> howto secrets

- docs/howto/abort.adoc
> howto abort

- docs/howto/repeatuntil.adoc
- how to repeat until a condition is met
> howto repeatuntil

- docs/howto/writestate.adoc
> howto writestate

- docs/howto/conditional.adoc
- cleanup documentation
- add error message for yaml that fail to load
- disable auto-conversion for quoted yaml state values
- fix breakpoint resume and abort on shutdown issue
- How to perform actions based on previous command results
> howto conditional

- docs/howto/foreach.adoc
> howto foreach

- docs/howto/patternforhost.adoc
- How to target host from command line
> howto patternforhost

- docs/howto/patternkeys.adoc
> howto patternkeys

- docs/howto/upload.adoc
> howto upload

- src/main/java/io/hyperfoil/tools/qdup/QDup.java
To allow for extension of Parser with custom commands.
Following discussion on https://github.com/Hyperfoil/qDup/pull/172, this PR does not create a Parser static
> Expose yaml parser from QDup

- src/main/java/io/hyperfoil/tools/qdup/SecretFilter.java
- src/test/java/io/hyperfoil/tools/qdup/SecretFilterTest.java
- [maven-release-plugin] prepare release qDup-0.6.18
- [maven-release-plugin] prepare for next development iteration
- check longest secrets first and require length > 0
> secrets 182

- docs/userguide.adoc
> some doc links fixed

- src/main/java/io/hyperfoil/tools/qdup/QDup.java
These modifications fix the issue #191
> improved shutdown hook management

- src/main/java/io/hyperfoil/tools/qdup/Local.java
- src/main/java/io/hyperfoil/tools/qdup/Run.java
- src/main/java/io/hyperfoil/tools/qdup/shell/ContainerShell.java
> close shell and threadpools for proper process shutdown

- src/test/java/io/hyperfoil/tools/qdup/SshTestBase.java
In fresh environment execute:
```
podman run -it ubuntu:23.04 bash
```
Then,
```
apt-get update
```
It will fail
> Change image to mirror.gcr.io/library/ubuntu:24.10
